package org.leesia.resource.res;

import org.leesia.dataio.service.CityService;
import org.leesia.dataio.service.ProvinceService;
import org.leesia.entity.City;
import org.leesia.entity.Province;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @Auther: leesia
 * @Date: 2018/8/8 19:22
 * @Description:
 */
@Service
public class CityResource {

    private Map<String, String> CITIES = new HashMap<>();

    @Autowired
    private ProvinceService provinceService;

    @Autowired
    private CityService cityService;

    public CityResource() {
        CITIES.put("北京市", "北京市");
        CITIES.put("上海市", "上海市");
        CITIES.put("天津市", "天津市");
        CITIES.put("重庆市", "重庆市");
        CITIES.put("安庆市", "安徽省");
        CITIES.put("蚌埠市", "安徽省");
        CITIES.put("巢湖市", "安徽省");
        CITIES.put("池州市", "安徽省");
        CITIES.put("滁州市", "安徽省");
        CITIES.put("阜阳市", "安徽省");
        CITIES.put("毫州市", "安徽省");
        CITIES.put("合肥市", "安徽省");
        CITIES.put("淮北市", "安徽省");
        CITIES.put("淮南市", "安徽省");
        CITIES.put("黄山市", "安徽省");
        CITIES.put("六安市", "安徽省");
        CITIES.put("马鞍山市", "安徽省");
        CITIES.put("宿州市", "安徽省");
        CITIES.put("铜陵市", "安徽省");
        CITIES.put("芜湖市", "安徽省");
        CITIES.put("宣城市", "安徽省");
        CITIES.put("福州市", "福建省");
        CITIES.put("龙岩市", "福建省");
        CITIES.put("南平市", "福建省");
        CITIES.put("宁德市", "福建省");
        CITIES.put("莆田市", "福建省");
        CITIES.put("泉州市", "福建省");
        CITIES.put("三明市", "福建省");
        CITIES.put("厦门市", "福建省");
        CITIES.put("漳州市", "福建省");
        CITIES.put("白银市", "甘肃省");
        CITIES.put("定西市", "甘肃省");
        CITIES.put("甘南州", "甘肃省");
        CITIES.put("嘉峪关市", "甘肃省");
        CITIES.put("金昌市", "甘肃省");
        CITIES.put("酒泉市", "甘肃省");
        CITIES.put("兰州市", "甘肃省");
        CITIES.put("临夏州", "甘肃省");
        CITIES.put("陇南市", "甘肃省");
        CITIES.put("平凉市", "甘肃省");
        CITIES.put("庆阳市", "甘肃省");
        CITIES.put("天水市", "甘肃省");
        CITIES.put("武威市", "甘肃省");
        CITIES.put("张掖市", "甘肃省");
        CITIES.put("潮州市", "广东省");
        CITIES.put("东莞市", "广东省");
        CITIES.put("佛山市", "广东省");
        CITIES.put("广州市", "广东省");
        CITIES.put("河源市", "广东省");
        CITIES.put("惠州市", "广东省");
        CITIES.put("江门市", "广东省");
        CITIES.put("揭阳市", "广东省");
        CITIES.put("茂名市", "广东省");
        CITIES.put("梅州市", "广东省");
        CITIES.put("清远市", "广东省");
        CITIES.put("汕头市", "广东省");
        CITIES.put("汕尾市", "广东省");
        CITIES.put("韶关市", "广东省");
        CITIES.put("深圳市", "广东省");
        CITIES.put("阳江市", "广东省");
        CITIES.put("云浮市", "广东省");
        CITIES.put("湛江市", "广东省");
        CITIES.put("肇庆市", "广东省");
        CITIES.put("中山市", "广东省");
        CITIES.put("珠海市", "广东省");
        CITIES.put("百色市", "广西壮族自治区");
        CITIES.put("北海市", "广西壮族自治区");
        CITIES.put("崇左市", "广西壮族自治区");
        CITIES.put("防城港市", "广西壮族自治区");
        CITIES.put("贵港市", "广西壮族自治区");
        CITIES.put("桂林市", "广西壮族自治区");
        CITIES.put("河池市", "广西壮族自治区");
        CITIES.put("贺州市", "广西壮族自治区");
        CITIES.put("来宾市", "广西壮族自治区");
        CITIES.put("柳州市", "广西壮族自治区");
        CITIES.put("南宁市", "广西壮族自治区");
        CITIES.put("钦州市", "广西壮族自治区");
        CITIES.put("梧州市", "广西壮族自治区");
        CITIES.put("玉林市", "广西壮族自治区");
        CITIES.put("安顺市", "贵州省");
        CITIES.put("毕节地区", "贵州省");
        CITIES.put("贵阳市", "贵州省");
        CITIES.put("六盘水市", "贵州省");
        CITIES.put("黔东南苗族侗族自治州", "贵州省");
        CITIES.put("黔南布依族苗族自治州", "贵州省");
        CITIES.put("黔西南布依族苗族自治州", "贵州省");
        CITIES.put("铜仁市", "贵州省");
        CITIES.put("遵义市", "贵州省");
        CITIES.put("海口市", "海南省");
        CITIES.put("三亚市", "海南省");
        CITIES.put("保定市", "河北省");
        CITIES.put("沧州市", "河北省");
        CITIES.put("承德市", "河北省");
        CITIES.put("邯郸市", "河北省");
        CITIES.put("衡水市", "河北省");
        CITIES.put("廊坊市", "河北省");
        CITIES.put("秦皇岛市", "河北省");
        CITIES.put("石家庄市", "河北省");
        CITIES.put("唐山市", "河北省");
        CITIES.put("邢台市", "河北省");
        CITIES.put("张家口市", "河北省");
        CITIES.put("安阳市", "河南省");
        CITIES.put("鹤壁市", "河南省");
        CITIES.put("焦作市", "河南省");
        CITIES.put("开封市", "河南省");
        CITIES.put("洛阳市", "河南省");
        CITIES.put("漯河市", "河南省");
        CITIES.put("南阳市", "河南省");
        CITIES.put("平顶山市", "河南省");
        CITIES.put("濮阳市", "河南省");
        CITIES.put("三门峡市", "河南省");
        CITIES.put("商丘市", "河南省");
        CITIES.put("新乡市", "河南省");
        CITIES.put("信阳市", "河南省");
        CITIES.put("许昌市", "河南省");
        CITIES.put("郑州市", "河南省");
        CITIES.put("周口市", "河南省");
        CITIES.put("驻马店市", "河南省");
        CITIES.put("大庆市", "黑龙江省");
        CITIES.put("大兴安岭地区", "黑龙江省");
        CITIES.put("哈尔滨市", "黑龙江省");
        CITIES.put("鹤岗市", "黑龙江省");
        CITIES.put("黑河市", "黑龙江省");
        CITIES.put("鸡西市", "黑龙江省");
        CITIES.put("佳木斯市", "黑龙江省");
        CITIES.put("牡丹江市", "黑龙江省");
        CITIES.put("七台河市", "黑龙江省");
        CITIES.put("齐齐哈尔市", "黑龙江省");
        CITIES.put("双鸭山市", "黑龙江省");
        CITIES.put("绥化市", "黑龙江省");
        CITIES.put("伊春市", "黑龙江省");
        CITIES.put("鄂州市", "湖北省");
        CITIES.put("恩施土家族苗族自治州", "湖北省");
        CITIES.put("黄冈市", "湖北省");
        CITIES.put("黄石市", "湖北省");
        CITIES.put("荆门市", "湖北省");
        CITIES.put("荆州市", "湖北省");
        CITIES.put("十堰市", "湖北省");
        CITIES.put("随州市", "湖北省");
        CITIES.put("武汉市", "湖北省");
        CITIES.put("咸宁市", "湖北省");
        CITIES.put("襄樊市", "湖北省");
        CITIES.put("孝感市", "湖北省");
        CITIES.put("宜昌市", "湖北省");
        CITIES.put("长沙市", "湖南省");
        CITIES.put("常德市", "湖南省");
        CITIES.put("郴州市", "湖南省");
        CITIES.put("衡阳市", "湖南省");
        CITIES.put("怀化市", "湖南省");
        CITIES.put("娄底市", "湖南省");
        CITIES.put("邵阳市", "湖南省");
        CITIES.put("湘潭市", "湖南省");
        CITIES.put("湘西土家族苗族自治州", "湖南省");
        CITIES.put("益阳市", "湖南省");
        CITIES.put("永州市", "湖南省");
        CITIES.put("岳阳市", "湖南省");
        CITIES.put("张家界市", "湖南省");
        CITIES.put("株洲市", "湖南省");
        CITIES.put("白城市", "吉林省");
        CITIES.put("白山市", "吉林省");
        CITIES.put("长春市", "吉林省");
        CITIES.put("吉林市", "吉林省");
        CITIES.put("辽源市", "吉林省");
        CITIES.put("四平市", "吉林省");
        CITIES.put("松原市", "吉林省");
        CITIES.put("通化市", "吉林省");
        CITIES.put("延边朝鲜族自治州", "吉林省");
        CITIES.put("常州市", "江苏省");
        CITIES.put("淮安市", "江苏省");
        CITIES.put("连云港市", "江苏省");
        CITIES.put("南京市", "江苏省");
        CITIES.put("南通市", "江苏省");
        CITIES.put("苏州市", "江苏省");
        CITIES.put("宿迁市", "江苏省");
        CITIES.put("泰州市", "江苏省");
        CITIES.put("无锡市", "江苏省");
        CITIES.put("徐州市", "江苏省");
        CITIES.put("盐城市", "江苏省");
        CITIES.put("扬州市", "江苏省");
        CITIES.put("镇江市", "江苏省");
        CITIES.put("抚州市", "江西省");
        CITIES.put("赣州市", "江西省");
        CITIES.put("吉安市", "江西省");
        CITIES.put("景德镇市", "江西省");
        CITIES.put("九江市", "江西省");
        CITIES.put("南昌市", "江西省");
        CITIES.put("萍乡市", "江西省");
        CITIES.put("上饶市", "江西省");
        CITIES.put("新余市", "江西省");
        CITIES.put("宜春市", "江西省");
        CITIES.put("鹰潭市", "江西省");
        CITIES.put("鞍山市", "辽宁省");
        CITIES.put("本溪市", "辽宁省");
        CITIES.put("朝阳市", "辽宁省");
        CITIES.put("大连市", "辽宁省");
        CITIES.put("丹东市", "辽宁省");
        CITIES.put("抚顺市", "辽宁省");
        CITIES.put("阜新市", "辽宁省");
        CITIES.put("葫芦岛市", "辽宁省");
        CITIES.put("锦州市", "辽宁省");
        CITIES.put("辽阳市", "辽宁省");
        CITIES.put("盘锦市", "辽宁省");
        CITIES.put("沈阳市", "辽宁省");
        CITIES.put("铁岭市", "辽宁省");
        CITIES.put("营口市", "辽宁省");
        CITIES.put("阿拉善盟", "内蒙古自治区");
        CITIES.put("巴彦淖尔市", "内蒙古自治区");
        CITIES.put("包头市", "内蒙古自治区");
        CITIES.put("赤峰市", "内蒙古自治区");
        CITIES.put("鄂尔多斯市", "内蒙古自治区");
        CITIES.put("呼和浩特市", "内蒙古自治区");
        CITIES.put("呼伦贝尔市", "内蒙古自治区");
        CITIES.put("通辽市", "内蒙古自治区");
        CITIES.put("乌海市", "内蒙古自治区");
        CITIES.put("乌兰察布市", "内蒙古自治区");
        CITIES.put("锡林郭勒盟", "内蒙古自治区");
        CITIES.put("兴安盟", "内蒙古自治区");
        CITIES.put("固原市", "宁夏回族自治区");
        CITIES.put("石嘴山市", "宁夏回族自治区");
        CITIES.put("吴忠市", "宁夏回族自治区");
        CITIES.put("银川市", "宁夏回族自治区");
        CITIES.put("中卫市", "宁夏回族自治区");
        CITIES.put("果洛藏族自治州", "青海省");
        CITIES.put("海北藏族自治州", "青海省");
        CITIES.put("海东地区", "青海省");
        CITIES.put("海南藏族自治州", "青海省");
        CITIES.put("海西蒙古族藏族自治州", "青海省");
        CITIES.put("黄南藏族自治州", "青海省");
        CITIES.put("西宁市", "青海省");
        CITIES.put("玉树藏族自治州", "青海省");
        CITIES.put("滨州市", "山东省");
        CITIES.put("德州市", "山东省");
        CITIES.put("东营市", "山东省");
        CITIES.put("菏泽市", "山东省");
        CITIES.put("济南市", "山东省");
        CITIES.put("济宁市", "山东省");
        CITIES.put("莱芜市", "山东省");
        CITIES.put("聊城市", "山东省");
        CITIES.put("临沂市", "山东省");
        CITIES.put("青岛市", "山东省");
        CITIES.put("日照市", "山东省");
        CITIES.put("泰安市", "山东省");
        CITIES.put("威海市", "山东省");
        CITIES.put("潍坊市", "山东省");
        CITIES.put("烟台市", "山东省");
        CITIES.put("枣庄市", "山东省");
        CITIES.put("淄博市", "山东省");
        CITIES.put("长治市", "山西省");
        CITIES.put("大同市", "山西省");
        CITIES.put("晋城市", "山西省");
        CITIES.put("晋中市", "山西省");
        CITIES.put("临汾市", "山西省");
        CITIES.put("吕梁市", "山西省");
        CITIES.put("朔州市", "山西省");
        CITIES.put("太原市", "山西省");
        CITIES.put("忻州市", "山西省");
        CITIES.put("阳泉市", "山西省");
        CITIES.put("运城市", "山西省");
        CITIES.put("安康市", "陕西省");
        CITIES.put("宝鸡市", "陕西省");
        CITIES.put("汉中市", "陕西省");
        CITIES.put("商洛市", "陕西省");
        CITIES.put("铜川市", "陕西省");
        CITIES.put("渭南市", "陕西省");
        CITIES.put("西安市", "陕西省");
        CITIES.put("咸阳市", "陕西省");
        CITIES.put("延安市", "陕西省");
        CITIES.put("榆林市", "陕西省");
        CITIES.put("阿坝藏族羌族自治州", "四川省");
        CITIES.put("巴中市", "四川省");
        CITIES.put("成都市", "四川省");
        CITIES.put("达州市", "四川省");
        CITIES.put("德阳市", "四川省");
        CITIES.put("甘孜藏族自治州", "四川省");
        CITIES.put("广安市", "四川省");
        CITIES.put("广元市", "四川省");
        CITIES.put("乐山市", "四川省");
        CITIES.put("凉山彝族自治州", "四川省");
        CITIES.put("泸州市", "四川省");
        CITIES.put("眉山市", "四川省");
        CITIES.put("绵阳市", "四川省");
        CITIES.put("内江市", "四川省");
        CITIES.put("南充市", "四川省");
        CITIES.put("攀枝花市", "四川省");
        CITIES.put("遂宁市", "四川省");
        CITIES.put("雅安市", "四川省");
        CITIES.put("宜宾市", "四川省");
        CITIES.put("资阳市", "四川省");
        CITIES.put("自贡市", "四川省");
        CITIES.put("阿里地区", "西藏自治区");
        CITIES.put("昌都地区", "西藏自治区");
        CITIES.put("拉萨市", "西藏自治区");
        CITIES.put("林芝地区", "西藏自治区");
        CITIES.put("那曲地区", "西藏自治区");
        CITIES.put("日喀则地区", "西藏自治区");
        CITIES.put("山南地区", "西藏自治区");
        CITIES.put("阿克苏地区", "新疆维吾尔自治区");
        CITIES.put("阿勒泰地区", "新疆维吾尔自治区");
        CITIES.put("巴音郭楞蒙古自治州", "新疆维吾尔自治区");
        CITIES.put("博尔塔拉蒙古自治州", "新疆维吾尔自治区");
        CITIES.put("昌吉回族自治州", "新疆维吾尔自治区");
        CITIES.put("哈密地区", "新疆维吾尔自治区");
        CITIES.put("和田地区", "新疆维吾尔自治区");
        CITIES.put("喀什地区", "新疆维吾尔自治区");
        CITIES.put("克拉玛依市", "新疆维吾尔自治区");
        CITIES.put("克孜勒苏柯尔克孜自治州", "新疆维吾尔自治区");
        CITIES.put("塔城地区", "新疆维吾尔自治区");
        CITIES.put("吐鲁番地区", "新疆维吾尔自治区");
        CITIES.put("乌鲁木齐市", "新疆维吾尔自治区");
        CITIES.put("伊犁哈萨克自治州", "新疆维吾尔自治区");
        CITIES.put("保山市", "云南省");
        CITIES.put("楚雄彝族自治州", "云南省");
        CITIES.put("大理白族自治州", "云南省");
        CITIES.put("德宏傣族景颇族自治州", "云南省");
        CITIES.put("迪庆藏族自治州", "云南省");
        CITIES.put("红河哈尼族彝族自治州", "云南省");
        CITIES.put("昆明市", "云南省");
        CITIES.put("丽江市", "云南省");
        CITIES.put("临沧市", "云南省");
        CITIES.put("怒江傈僳族自治州", "云南省");
        CITIES.put("普洱市", "云南省");
        CITIES.put("曲靖市", "云南省");
        CITIES.put("文山壮族苗族自治州", "云南省");
        CITIES.put("西双版纳傣族自治州", "云南省");
        CITIES.put("玉溪市", "云南省");
        CITIES.put("昭通市", "云南省");
        CITIES.put("杭州市", "浙江省");
        CITIES.put("湖州市", "浙江省");
        CITIES.put("嘉兴市", "浙江省");
        CITIES.put("金华市", "浙江省");
        CITIES.put("丽水市", "浙江省");
        CITIES.put("宁波市", "浙江省");
        CITIES.put("衢州市", "浙江省");
        CITIES.put("绍兴市", "浙江省");
        CITIES.put("台州市", "浙江省");
        CITIES.put("温州市", "浙江省");
        CITIES.put("舟山市", "浙江省");
    }

    private List<City> createAllCities() throws Exception {
        List<Province> provinces = provinceService.get(new HashMap<>());
        Map<String, Province> provinceMap = new HashMap<>();
        for (Province province : provinces) {
            provinceMap.put(province.getProvinceName(), province);
        }
        List<City> cities = new ArrayList<>();
        for (Map.Entry<String, String> entry : CITIES.entrySet()) {
            if (!provinceMap.containsKey(entry.getValue())) {
                throw new Exception("省份不存在：" + entry.getValue());
            }
            Province province = provinceMap.get(entry.getValue());
            City city = new City();
            city.setCityName(entry.getKey());
            city.setProvince(province.getId());
            city.setProvinceName(province.getProvinceName());

            cities.add(city);
        }

        return cities;
    }

    public void insertAllCity() throws Exception {
        cityService.batchInsert(createAllCities());
    }
}
