spring:
    application:
        name: people-resources
    datasource:
            name: leesia
            url: jdbc:mysql://192.168.8.137:3306/people?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Hongkong
            username: root
            password: mysql
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        host: 192.168.8.137
        port: 6379
        timeout: 20000
#        cluster:
#            nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
#            maxRedirects: 6
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1

mybatis:
    mapper-locations: classpath*:mybatis/*/*.xml
    type-aliases-package: org.leesia.entity