CREATE TABLE AGE_DISTRIBUTION (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `MIN_AGE` int(11) DEFAULT NULL COMMENT '最小年龄，包括',
  `MAX_AGE` int(11) DEFAULT NULL COMMENT '最大年龄，不包括',
  `DISTRIBUTION` DOUBLE(10,8) NOT NULL COMMENT '年龄分布',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MM_AGE` (`MIN_AGE`, `MAX_AGE`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='年龄分布表';