CREATE TABLE `CITY` (
  `ID` char(32) NOT NULL COMMENT '主键',
  `CITY_CODE` varchar(15) DEFAULT NULL COMMENT '城市编码',
  `CITY_NAME` varchar(50) NOT NULL COMMENT '城市名称',
  `PROVINCE` char(32) DEFAULT NULL COMMENT '所在省ID',
  `PROVINCE_NAME` varchar(50) DEFAULT NULL COMMENT '所在省名称',
  `CREATE_DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CITY_NAME` (`CITY_NAME`),
  KEY `PROVINCE` (`PROVINCE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='城市表';

