CREATE TABLE COMMON_HANZI (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `HANZI` CHAR(2) NOT NULL COMMENT '常用汉字',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `HANZI` (`HANZI`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='常用汉字表';