CREATE TABLE COMMON_HANZI (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `HANZI` VARCHAR(4) NOT NULL COMMENT '常用汉字',
  `IS_NAME` TINYINT(1) DEFAULT NULL COMMENT '是否用作名字',
  `IS_SECOND` TINYINT(1) DEFAULT NULL COMMENT '名字中作为第二个字',
  `IS_THIRD` TINYINT(1) DEFAULT NULL COMMENT '名字中作为第三个字',
  `IS_MALE` TINYINT(1) DEFAULT NULL COMMENT '是否男性名字用字',
  `IS_FEMALE` TINYINT(1) DEFAULT NULL COMMENT '是否女性名字用字',
  `MALE_PERFECT` TINYINT(1) DEFAULT NULL COMMENT '男生常用名字',
  `FEMALE_PERFECT` TINYINT(1) DEFAULT NULL COMMENT '女生常用名字',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `HANZI` (`HANZI`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='常用汉字表';