CREATE TABLE ID_NUMBER_DISTRIBUTION (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `PROVINCE` char(32) DEFAULT NULL COMMENT '省份ID',
  `PROVINCE_NAME` varchar(50) DEFAULT NULL COMMENT '省份名称',
  `ID_NUMBER` varchar(2000) NOT NULL COMMENT '身份证号码前缀分布，逗号分隔',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROVINCE` (`PROVINCE`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='身份证号码前缀分布表';