CREATE TABLE LAST_NAME_DISTRIBUTION (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `LAST_NAME` VARCHAR(10) NOT NULL COMMENT '姓氏',
  `DISTRIBUTION` DOUBLE(10,8) NOT NULL COMMENT '姓氏人口分布',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LAST_NAME` (`LAST_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='姓氏人口分布表';