CREATE TABLE PERSON (
  `ID` CHAR(18) NOT NULL COMMENT '身份证号，主键',
  `NAME` VARCHAR(10) NOT NULL COMMENT '姓名',
  `SEX` INT(3) NOT NULL COMMENT '性别',
  `BIRTHDAY` VARCHAR(10) NOT NULL COMMENT '出生日期',
  `NATION` VARCHAR(20) NOT NULL COMMENT '民族',
  `REGISTER_PROVINCE` VARCHAR(50) NOT NULL COMMENT '户籍省份',
  `REGISTER_CITY` VARCHAR(50) NOT NULL COMMENT '户籍城市',
  `LIVE_PROVINCE` VARCHAR(50) DEFAULT NULL COMMENT '居住省份',
  `LIVE_CITY` VARCHAR(50) DEFAULT NULL COMMENT '居住城市',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  KEY `NAME` (`NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='个人表';