CREATE TABLE `PROVINCE` (
  `ID` char(32) NOT NULL COMMENT '主键',
  `PROVINCE_CODE` varchar(15) DEFAULT NULL COMMENT '省份编码',
  `PROVINCE_NAME` varchar(50) NOT NULL COMMENT '省份名称',
  `PROVINCE_SHORT_NAME` varchar(15) DEFAULT NULL COMMENT '省份简称',
  `CAPITAL` char(32) DEFAULT NULL COMMENT '首府城市ID',
  `CAPITAL_NAME` varchar(50) DEFAULT NULL COMMENT '首府城市名',
  `CREATE_DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROVINCE_CODE` (`PROVINCE_CODE`),
  UNIQUE KEY `PROVINCE_NAME` (`PROVINCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='省份表';