CREATE TABLE PROVINCE_DISTRIBUTION (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `PROVINCE_NAME` VARCHAR(20) NOT NULL COMMENT '省份名称',
  `DISTRIBUTION` DOUBLE(10,8) DEFAULT NULL COMMENT '人口分布',
  `NATION_DISTRIBUTION` VARCHAR(1000) DEFAULT NULL COMMENT '民族分布，JSON串',
  `SEX_DISTRIBUTION` VARCHAR(100) DEFAULT NULL COMMENT '性别分布，JSON串',
  `LAST_NAME_DISTRIBUTION` VARCHAR(1000) DEFAULT NULL COMMENT '姓氏分布，JSON串',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROVINCE_NAME` (`PROVINCE_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='省份人口分布表';