CREATE TABLE PROVINCE (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `PROVINCE_NAME` VARCHAR(50) NOT NULL COMMENT '省份名称',
  `CAPITAL` CHAR(32) DEFAULT NULL COMMENT '首府城市ID',
  `CAPITAL_NAME` VARCHAR(50) DEFAULT NULL COMMENT '首府城市名',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROVINCE_NAME` (`PROVINCE_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='省份表';