CREATE TABLE SEX_DISTRIBUTION (
  `ID` CHAR(32) NOT NULL COMMENT '主键',
  `SEX` int(11) DEFAULT NULL COMMENT '性别，0：男性；1：女性',
  `DISTRIBUTION` DOUBLE(10,8) NOT NULL COMMENT '性别分布',
  `CREATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期时间',
  `UPDATE_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SEX` (`SEX`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='性别分布表';